theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

title: m1kkY8 # the main title

description: >- # used by seo meta and the atom feed
  Simple blog for sharing writeups and such

url: "https://m1kky8.github.io"

github:
  username: m1kkY8

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Milan
  #email: example@domain.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/m1kkY8 # change to your github homepage
    - https://tryhackme.com/r/p/m1kkY8
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username
